name: Android CI/CD Manual Mac

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Tipe Build'
        required: true
        default: 'debug'
        type: choice
        options:
        - debug
        - release

env:
  SAMPLE_PATH: .

jobs:
  build:
    name: Build and Test
    runs-on: macos-26

    steps:
      - name: Checkout
        uses: actions/checkout@v4 # Versi stabil terbaru

      # Memastikan folder ~/.gradle ada dan menyalin config khusus CI
      - name: Copy CI gradle.properties
        run: |
          mkdir -p ~/.gradle
          if [ -f .github/ci-gradle.properties ]; then
            cp .github/ci-gradle.properties ~/.gradle/gradle.properties
          else
            echo "Warning: .github/ci-gradle.properties tidak ditemukan!"
          fi

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # Action resmi Gradle untuk optimasi cache otomatis
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build project
        working-directory: ${{ env.SAMPLE_PATH }}
        run: ./gradlew assembleDebug lintDebug --stacktrace

      - name: Upload build outputs (APKs)
        uses: actions/upload-artifact@v4
        with:
          name: build-outputs
          path: ${{ env.SAMPLE_PATH }}/app/build/outputs/apk/debug

      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: ${{ env.SAMPLE_PATH }}/app/build/reports